services:
  flask_fileserver:
    container_name: flask_fileserver
    build: .
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /home/cam/File-Server/files
        target: /files
        volume:
            nocopy: true
    image: cam/fileserver
